### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by jaumeortola** [jaumeortola/hyphen-ca#1]
- [x] Baudelaire: Bau-de-laire
- [x] l’Spor-ting
- [x] Su-ble-var, su-ble-va-ci-ó
- [x] shake-spear-i-à (però el GDLC té sha_kes_pe_a_ri_à)
- [x] super... (com a prefix)
- [x] aguar (dades en la Gramàtica de l'IEC)

**Comment by jmontane** [comment]
- [x] Indicar les paraules homògrafes que poden tenir partició/pronúncia diferent, segons el significat:
   - [x] pius: Pi-us vs. pius
   - [x] periòdic, periòdics, periòdica, periòdiques: per-iò-dic vs. pe-ri-ò-dic
   - [x] aguant: a-gu-ant vs. a-guant
   - [x] trair: tra-ir vs. trair (trairar)
   - [x] trairem: tra-i-rem vs. trai-rem (trairar)
   - [x] traireu: tra-i-reu vs. trai-reu (trairar)
   - [x] trairen: tra-i-ren vs. trai-ren (trairar)
   - [x] trairàs: tra-i-ràs vs. trai-ràs (trairar)
   - [x] pair: pa-ir vs. pair (pairar)
   - [x] pairem: pa-i-rem vs. pai-rem (pairar)
   - [x] paireu: pa-i-reu vs. pai-reu (pairar)
   - [x] pairen: pa-i-ren vs. pai-ren (pairar)
   - [x] pairàs: pa-i-ràs vs. pai-ràs (pairar)

- [ ] Detectar i indicar les particions que fem diferents del GDLC:
   - [x] zim-ba-bu-ès (diferent del GCLC, zim-ba-buès), també femení i plurals
   - [x] shake-spear-i-à (diferent del GDLC, sha-kes-pe-a-ri-à) també femení i plurals
   - [x] si-khis-me, si-khis-ta (diferent del GDLC)

- [ ] Coses pendents i, si escau, indicar-ho:
  - [x] tractar el dígraf sh: problemes amb els prefixos des- i trans-, cap altre? Potser les regles 1s2h[aeiouàèéíòóú] .de2s3h, .tran2s3h serien suficients?
  - [x] tractar el dígraf lh? Almenys per a lherzolita.
  - [x] tractar els dígrafs th i ph?
  - [x] tractar la y entre vocals.
  - [x] aguar (calen excepcions).
  - [x] excepcions per als nombres romans. P. ex. , xvii, xxiii...
   - [x] millorar el tractament de la w semivocàlica: s_wing, t_wist, welwíts_qui_a zim_babwès (i derivats).
- [ ] Coses a considerar i, si escau, indicar-ho:
   - [x] argüir: amb la regla ü3ï donaríem cobertura a la proposta d'E. Valor per a aquest verb.
   - [x] grúids, escarabèids,... : amb les regles ú1id. i ú1ids. (i equivalents) donaríem cobertura a la grafia antiga d'aquests mots.
   - [x] ambigüitat, ambigüitats: el GDLC indica diftong a güi. Ho donem per bo? (c.f. continuïtat)

**Comment by jaumeortola** [comment]
- [ ] Campañà

**Comment by jaumeortola** [comment]
- [x] es-tat-u-ni-denc

**Comment by jaumeortola** [comment]
(de Pere Farrando)
- [x] freelance
- [x] ganache
- [x] ganaches
- [x] Hollywood hol_ly_wood
- [x] hollywoodiana
- [x] hollywoodianes hol_ly_woo_di_a_nes
- [x] hollywoodians
- [x] hollywoodià
- [x] khmer
- [x] khmers
- [x] Liechtenstein
- [x] Massachusetts
- [x] rockabilly
- [x] Springsteen
- [x] sud-africana
- [x] sud-africanes
- [x] sud-africans
- [x] sud-africà
- [x] sud-americana
- [x] sud-americanes
- [x] sud-americà

**Comment by jaumeortola** [comment]
- [x] Mon-taigne
- [x] start-up
- [x] Pas-cual
- [x] Beet-ho-ven

**Comment by jaumeortola** [comment]
- [x] interés

**Comment by jmontane** [comment]
- [ ] Les regles d'inici de mot (les que comencen amb punt) seguides de vocal o hac haurien d'estar doblades amb apòstrof, perquè s'apliquin també en el cas d'article apostrofat. Per exemple:

La regla `.a4n3alfabet` permet obtenir
`analfabet > an|al|fa|bet` (correcte)

Però ara també obtenim
`l'analfabet > l'a|nal|fa|bet` (incorrecte)

Caldria afegir la regla `'a4n3alfabet`. No veig una altra manera de fer bé la partició amb apòstrof
